sudo: false

cache: bundler

branch:
  only: master

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - rbx-3.14
  - jruby-9.0.5.0

gemfile:
  - gemfiles/rack1.0.gemfile
  - gemfiles/rack2.0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rack2.0.gemfile
